import Navbar from '@/components/Navbar'
import './globals.css'
import { DM_Sans } from 'next/font/google'
import Footer from '@/components/Footer'

const inter = DM_Sans({ 
  weight: ['400','500','700'],
  subsets: ['latin'] 
})

export const metadata = {
  title: 'Landing App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#FFFFFF] min-w-full flex flex-col min-h-full`}>
        <Navbar />
        <main className='flex-grow'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
